/**
 * AES-192 / AES-256 in ECB + CBC — known-answer tests.
 *
 * ## Why this file exists
 *
 * Phase B of `docs/plans/foamy-prancing-wren.md` extended the multi-block modes
 * from AES-128 to all three variants. On paper that was "a table-only change":
 * the mode builders were already variant-parameterized via `BlockCipherCore`,
 * so AES-192/256 ECB/CBC cost two lines in `stores/spec.ts`.
 *
 * "Should work by construction" is exactly the claim a KAT exists to check.
 * These specs are generated by a code path no test had ever run — `aesCore` at
 * Nk=6 and Nk=8 driving `buildEcbSpec`/`buildCbcSpec` — and the failure mode
 * is silent: a wrong round count or a mis-sized key read produces plausible
 * ciphertext that is simply wrong. So each variant is pinned against the
 * PUBLISHED NIST vectors and, independently, against `node:crypto`.
 *
 * Vectors: NIST SP 800-38A §F.1.3/§F.1.4 (ECB-AES192), §F.1.5/§F.1.6
 * (ECB-AES256), §F.2.3/§F.2.4 (CBC-AES192), §F.2.5/§F.2.6 (CBC-AES256).
 * Same 4-block plaintext as every other appendix-F example, so the variants
 * line up side-by-side with the shipped AES-128 KATs.
 */

import { createCipheriv, createDecipheriv } from "node:crypto";
import { aesCore } from "@/ciphers/aes-core";
import { buildDefaultRegistry } from "@/ciphers/default-registry";
import { buildCbcSpec } from "@/ciphers/modes/cbc";
import { buildEcbSpec } from "@/ciphers/modes/ecb";
import { runSpec } from "@/core/runtime";
import { applyPaddingScheme } from "@/core/spec-mutations";
import { bytesFromHex, hexFromBytes, makeBytesState } from "@/core/state/bytes";
import type { AuxValue, CipherSpec } from "@/core/types";
import { describe, expect, it } from "vitest";

// SP 800-38A §F keys (shared across the ECB and CBC examples).
const KEY_192 = "8e73b0f7da0e6452c810f32b809079e562f8ead2522c6b7b";
const KEY_256 = "603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4";
const IV = "000102030405060708090a0b0c0d0e0f";

const PLAINTEXT_4_BLOCKS =
  "6bc1bee22e409f96e93d7e117393172a" +
  "ae2d8a571e03ac9c9eb76fac45af8e51" +
  "30c81c46a35ce411e5fbc1191a0a52ef" +
  "f69f2445df4f9b17ad2b417be66c3710";

// §F.1.3 (ECB-AES192.Encrypt)
const ECB_192_CT =
  "bd334f1d6e45f25ff712a214571fa5cc" +
  "974104846d0ad3ad7734ecb3ecee4eef" +
  "ef7afd2270e2e60adce0ba2face6444e" +
  "9a4b41ba738d6c72fb16691603c18e0e";

// §F.1.5 (ECB-AES256.Encrypt)
const ECB_256_CT =
  "f3eed1bdb5d2a03c064b5a7e3db181f8" +
  "591ccb10d410ed26dc5ba74a31362870" +
  "b6ed21b99ca6f4f9f153e7b1beafed1d" +
  "23304b7a39f9f3ff067d8d8f9e24ecc7";

// §F.2.3 (CBC-AES192.Encrypt)
const CBC_192_CT =
  "4f021db243bc633d7178183a9fa071e8" +
  "b4d9ada9ad7dedf4e5e738763f69145a" +
  "571b242012fb7ae07fa9baac3df102e0" +
  "08b0e27988598881d920a9e64f5615cd";

// §F.2.5 (CBC-AES256.Encrypt)
const CBC_256_CT =
  "f58c4c04d6e5f1ba779eabfb5f7bfbd6" +
  "9cfc4e967edb808d679f777bc6702c7d" +
  "39f23369a9d9bacfa530e26304231461" +
  "b2eb05e2c39be9fcda6c19078c6a9d1b";

const run = (spec: CipherSpec, inputHex: string, aux: Map<string, AuxValue>): string => {
  const trace = runSpec(spec, buildDefaultRegistry(), {
    initialState: makeBytesState(bytesFromHex(inputHex)),
    initialAux: aux,
  });
  if (trace.finalState.shape !== "bytes") throw new Error("expected bytes final state");
  return hexFromBytes(trace.finalState.bytes);
};

const ecbAux = (keyHex: string): Map<string, AuxValue> =>
  new Map<string, AuxValue>([["key", bytesFromHex(keyHex)]]);

const cbcAux = (keyHex: string): Map<string, AuxValue> =>
  new Map<string, AuxValue>([
    ["key", bytesFromHex(keyHex)],
    ["iv", bytesFromHex(IV)],
  ]);

describe.each([
  { variant: "aes-192", keyHex: KEY_192, ecbCt: ECB_192_CT, cbcCt: CBC_192_CT },
  { variant: "aes-256", keyHex: KEY_256, ecbCt: ECB_256_CT, cbcCt: CBC_256_CT },
] as const)(
  "$variant multi-block modes (NIST SP 800-38A §F)",
  ({ variant, keyHex, ecbCt, cbcCt }) => {
    const core = aesCore(variant);

    it("ECB encrypts the 4-block plaintext to the published ciphertext", () => {
      expect(run(buildEcbSpec(core, "encrypt"), PLAINTEXT_4_BLOCKS, ecbAux(keyHex))).toBe(ecbCt);
    });

    it("ECB decrypts the published ciphertext back to the plaintext", () => {
      expect(run(buildEcbSpec(core, "decrypt"), ecbCt, ecbAux(keyHex))).toBe(PLAINTEXT_4_BLOCKS);
    });

    it("CBC encrypts the 4-block plaintext to the published ciphertext", () => {
      // ≥3 blocks, so the chain feedback is exercised feedback-of-feedback: a
      // wrong carry shows up from block 2 onward rather than being masked.
      expect(run(buildCbcSpec(core, "encrypt"), PLAINTEXT_4_BLOCKS, cbcAux(keyHex))).toBe(cbcCt);
    });

    it("CBC decrypts the published ciphertext back to the plaintext", () => {
      expect(run(buildCbcSpec(core, "decrypt"), cbcCt, cbcAux(keyHex))).toBe(PLAINTEXT_4_BLOCKS);
    });

    it("matches node:crypto on an arbitrary 3-block message (ECB + CBC)", () => {
      // Independent oracle, on a message NIST never published — so this can't
      // pass by a vector having been transcribed into the expectation twice.
      const ptHex =
        "00112233445566778899aabbccddeeff" +
        "0f1e2d3c4b5a69788796a5b4c3d2e1f0" +
        "fedcba98765432100123456789abcdef";
      const ivHex = "f0e1d2c3b4a5968778695a4b3c2d1e0f";

      const nodeRef = (algo: string, iv: string | null): string => {
        const c = createCipheriv(
          algo,
          Buffer.from(keyHex, "hex"),
          iv ? Buffer.from(iv, "hex") : null,
        );
        c.setAutoPadding(false); // the message is an exact block multiple
        return Buffer.concat([c.update(Buffer.from(ptHex, "hex")), c.final()]).toString("hex");
      };

      expect(run(buildEcbSpec(core, "encrypt"), ptHex, ecbAux(keyHex))).toBe(
        nodeRef(`${variant}-ecb`, null),
      );

      const cbcSpecAux = new Map<string, AuxValue>([
        ["key", bytesFromHex(keyHex)],
        ["iv", bytesFromHex(ivHex)],
      ]);
      expect(run(buildCbcSpec(core, "encrypt"), ptHex, cbcSpecAux)).toBe(
        nodeRef(`${variant}-cbc`, ivHex),
      );
    });

    it("CBC + PKCS#7 round-trips a NON-block-multiple message", () => {
      // The one path where the padding overlay and a non-AES-128 body actually
      // MEET. Every other test here runs scheme=none on exact block multiples,
      // and the overlay's own tests all run AES-128 — so "AES-192 + CBC +
      // PKCS#7, type 20 bytes, hit Run" (a newly-reachable user path) had never
      // executed end-to-end. Both halves being separately covered is exactly
      // the composition that "works by construction" right up until the
      // decrypt's `outputFrom` rewrite meets a real multi-block non-128 body.
      const shortPtHex = "00112233445566778899aabbccddeeff01020304"; // 20 bytes → pads to 32
      const ivHex = "f0e1d2c3b4a5968778695a4b3c2d1e0f";
      const aux = (): Map<string, AuxValue> =>
        new Map<string, AuxValue>([
          ["key", bytesFromHex(keyHex)],
          ["iv", bytesFromHex(ivHex)],
        ]);

      // node:crypto with AUTO-padding on = the PKCS#7 oracle.
      const c = createCipheriv(
        `${variant}-cbc`,
        Buffer.from(keyHex, "hex"),
        Buffer.from(ivHex, "hex"),
      );
      c.setAutoPadding(true);
      const expectedCt = Buffer.concat([
        c.update(Buffer.from(shortPtHex, "hex")),
        c.final(),
      ]).toString("hex");

      const encSpec = applyPaddingScheme(buildCbcSpec(core, "encrypt"), "encrypt", "pkcs7", 16);
      expect(run(encSpec, shortPtHex, aux())).toBe(expectedCt);

      // ...and back, through the unpad + the moved `outputFrom`.
      const decSpec = applyPaddingScheme(buildCbcSpec(core, "decrypt"), "decrypt", "pkcs7", 16);
      expect(run(decSpec, expectedCt, aux())).toBe(shortPtHex);

      // Sanity that the oracle really padded: 20 bytes in, 32 out.
      const d = createDecipheriv(
        `${variant}-cbc`,
        Buffer.from(keyHex, "hex"),
        Buffer.from(ivHex, "hex"),
      );
      d.setAutoPadding(true);
      expect(
        Buffer.concat([d.update(Buffer.from(expectedCt, "hex")), d.final()]).toString("hex"),
      ).toBe(shortPtHex);
      expect(expectedCt.length / 2).toBe(32);
    });
  },
);
