/**
 * Tests for `aes.key-expansion@2`.
 *
 * Two properties drive this file:
 *
 *   1. **Parity with @1 at canonical round counts.** For each canonical
 *      (Nk, rounds) pair — (4, 10), (6, 12), (8, 14) — @2 must produce
 *      byte-identical round-key tables to @1. Without this, any saved
 *      document upgraded from @1 to @2 would produce a different cipher,
 *      which would silently break round-trip.
 *
 *   2. **Non-canonical rounds work end-to-end.** The duplicate-round
 *      feature's whole point: extend an AES-128 schedule to 11 rounds and
 *      get a valid extra round key whose Rcon entry was generated by the
 *      executor (not supplied by the spec). We verify:
 *        - rounds = 11 with the canonical 11-entry AES_RCON table
 *          (Rcon[1..10]) auto-extends Rcon[11] = xtime(Rcon[10]) = 0x6c.
 *        - The expansion produces 12 round keys (roundKey.0..roundKey.11),
 *          and roundKey.10 matches what @1 would have emitted at rounds=10
 *          (same first 11 round keys regardless of where we stop).
 *
 * The full end-to-end "AES-128 with 11 rounds round-trips" test lives in
 * `aes-duplicate-round.test.ts` once the rest of the duplicate-round
 * machinery (the mutator + store action + spec wiring) lands. Phase 1
 * here is the step-type contract in isolation.
 */

import { AES_RCON, AES_SBOX } from "@/ciphers/aes-constants";
import type { Json, StepContext } from "@/core/types";
import { keyExpansion, keyExpansionV2 } from "@/steps/key-expansion";
import { describe, expect, it } from "vitest";

// Slice 5.2 — `keyExpansion` / `keyExpansionV2` are now `PortedExecutor`s:
// the master key arrives on the `masterKey` input port (not via ctx.aux) and
// the round keys come back on output ports `key0` … `keyN` (not via auxWrites).
// `ctx` is ignored by the executor but the signature still requires it.
const CTX: StepContext = { stepId: "key-expansion", path: [], aux: new Map() };

const baseParams = (rounds: number): Json => ({
  keyAuxName: "key",
  outputPrefix: "roundKey",
  sbox: [...AES_SBOX] as readonly number[] as number[],
  rcon: [...AES_RCON] as readonly number[] as number[],
  rounds,
});

/** Call a key-expansion executor on the `masterKey` port; returns the round-key port map. */
const callKeyExpansion = (
  variant: "v1" | "v2",
  keyBytes: Uint8Array,
  rounds: number,
): ReadonlyMap<string, Uint8Array> => {
  const exec = variant === "v1" ? keyExpansion : keyExpansionV2;
  return exec(new Map([["masterKey", keyBytes]]), baseParams(rounds), CTX);
};

/** Run both executors against the same key and compare every round-key port byte-for-byte. */
const expectByteIdenticalToV1 = (keyBytes: Uint8Array, rounds: number): void => {
  const v1Out = callKeyExpansion("v1", keyBytes, rounds);
  const v2Out = callKeyExpansion("v2", keyBytes, rounds);
  expect(v2Out.size).toBe(v1Out.size);
  for (const [port, v1Value] of v1Out) {
    const v2Value = v2Out.get(port);
    expect(v2Value).toBeInstanceOf(Uint8Array);
    // Compare bytes — Uint8Array equality is reference, not value.
    expect(Array.from(v2Value as Uint8Array)).toEqual(Array.from(v1Value));
  }
};

describe("aes.key-expansion@2 — parity with @1 at canonical round counts", () => {
  it("AES-128 (Nk=4, rounds=10) — byte-identical round keys", () => {
    // Canonical FIPS-197 §A.1 key.
    const key = new Uint8Array([
      0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f,
      0x3c,
    ]);
    expectByteIdenticalToV1(key, 10);
  });

  it("AES-192 (Nk=6, rounds=12) — byte-identical round keys", () => {
    // FIPS-197 §A.2 key.
    const key = new Uint8Array([
      0x8e, 0x73, 0xb0, 0xf7, 0xda, 0x0e, 0x64, 0x52, 0xc8, 0x10, 0xf3, 0x2b, 0x80, 0x90, 0x79,
      0xe5, 0x62, 0xf8, 0xea, 0xd2, 0x52, 0x2c, 0x6b, 0x7b,
    ]);
    expectByteIdenticalToV1(key, 12);
  });

  it("AES-256 (Nk=8, rounds=14) — byte-identical round keys (covers Nk>6 branch)", () => {
    // FIPS-197 §A.3 key.
    const key = new Uint8Array([
      0x60, 0x3d, 0xeb, 0x10, 0x15, 0xca, 0x71, 0xbe, 0x2b, 0x73, 0xae, 0xf0, 0x85, 0x7d, 0x77,
      0x81, 0x1f, 0x35, 0x2c, 0x07, 0x3b, 0x61, 0x08, 0xd7, 0x2d, 0x98, 0x10, 0xa3, 0x09, 0x14,
      0xdf, 0xf4,
    ]);
    expectByteIdenticalToV1(key, 14);
  });
});

describe("aes.key-expansion@2 — non-canonical round counts", () => {
  it("AES-128 key, rounds=11 — auto-extends Rcon[11] = xtime(Rcon[10]) = 0x6c", () => {
    // The first 11 round keys must match @1 at rounds=10 (i.e. word 0..43
    // are identical regardless of where the schedule terminates). The new
    // roundKey.11 is what only @2 produces; we don't pin its exact bytes
    // (the duplicate-round end-to-end test covers semantic correctness via
    // a round-trip), but we DO assert it's a fresh 16-byte block and that
    // a 12-th word group exists.
    const key = new Uint8Array([
      0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f,
      0x3c,
    ]);

    const v1Out = callKeyExpansion("v1", key, 10);
    const v2Out = callKeyExpansion("v2", key, 11);

    // 11 round keys from v1 (rounds=10) + an extra one from v2 (rounds=11) = 12.
    expect(v1Out.size).toBe(11);
    expect(v2Out.size).toBe(12);

    // First 11 round keys identical.
    for (let r = 0; r <= 10; r++) {
      const v1rk = v1Out.get(`key${r}`) as Uint8Array;
      const v2rk = v2Out.get(`key${r}`) as Uint8Array;
      expect(Array.from(v2rk)).toEqual(Array.from(v1rk));
    }

    // The extra round key exists and is well-shaped.
    const extra = v2Out.get("key11");
    expect(extra).toBeInstanceOf(Uint8Array);
    expect((extra as Uint8Array).length).toBe(16);
  });

  it("AES-128 key, rounds=20 — Rcon auto-extension chains correctly", () => {
    // Push well past the seeded table to exercise the xtime chain.
    // Rcon table extends from index 11 onward by Rcon[i] = xtime(Rcon[i-1]).
    // Starting from Rcon[10] = 0x36:
    //   Rcon[11] = xtime(0x36) = 0x6c
    //   Rcon[12] = xtime(0x6c) = 0xd8
    //   Rcon[13] = xtime(0xd8) = 0xab (0xb0 ^ 0x1b)
    //   Rcon[14] = xtime(0xab) = 0x4d (0x56 ^ 0x1b)
    //   Rcon[15] = xtime(0x4d) = 0x9a
    //   Rcon[16] = xtime(0x9a) = 0x2f (0x34 ^ 0x1b)
    //   Rcon[17] = xtime(0x2f) = 0x5e
    //   Rcon[18] = xtime(0x5e) = 0xbc
    //   Rcon[19] = xtime(0xbc) = 0x63 (0x78 ^ 0x1b)
    //   Rcon[20] = xtime(0x63) = 0xc6
    // (We don't assert these — the test below cross-checks via a key with a
    // known property: any non-zero seed bit propagates non-trivially, so a
    // schedule of 20 rounds produces 21 distinct round keys.)
    const key = new Uint8Array([
      0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f,
      0x3c,
    ]);
    const out = callKeyExpansion("v2", key, 20);
    expect(out.size).toBe(21);
    // Cross-check: all round keys are 16 bytes; no two consecutive round
    // keys are bit-identical (Rcon ensures forward-shift can't degenerate
    // even if SubWord didn't fire). Cheap sanity that the chain is alive.
    let prev: Uint8Array | null = null;
    for (let r = 0; r <= 20; r++) {
      const rk = out.get(`key${r}`) as Uint8Array;
      expect(rk.length).toBe(16);
      if (prev !== null) {
        const identical = Array.from(rk).every((b, i) => b === (prev as Uint8Array)[i]);
        expect(identical).toBe(false);
      }
      prev = rk;
    }
  });

  it("rejects rounds < 1 with a clear error", () => {
    const key = new Uint8Array(16); // all-zero AES-128 key
    expect(() => callKeyExpansion("v2", key, 0)).toThrow(/rounds.*>= 1/);
  });

  it("rejects non-integer rounds with a clear error", () => {
    const key = new Uint8Array(16);
    expect(() => callKeyExpansion("v2", key, 10.5)).toThrow(/rounds.*integer/);
  });

  it("rejects an invalid key length", () => {
    const key = new Uint8Array(20); // not 16/24/32
    expect(() => callKeyExpansion("v2", key, 10)).toThrow(/16-, 24-, or 32-byte/);
  });
});

describe("aes.key-expansion@2 — registry integration", () => {
  it("is registered under the @2 key with its doc block", async () => {
    const { buildDefaultRegistry } = await import("@/ciphers/default-registry");
    const r = buildDefaultRegistry();
    expect(r.has("aes.key-expansion@2")).toBe(true);
    const doc = r.getDoc("aes.key-expansion@2");
    expect(doc).toBeDefined();
    expect(doc?.name).toBe("Key Expansion (v2)");
    expect(doc?.shapeContract).toEqual({ input: "any", output: "preserveInput" });
  });

  it("keeps @1 registered alongside @2", async () => {
    const { buildDefaultRegistry } = await import("@/ciphers/default-registry");
    const r = buildDefaultRegistry();
    expect(r.has("aes.key-expansion@1")).toBe(true);
    expect(r.has("aes.key-expansion@2")).toBe(true);
  });
});
