/**
 * OFB known-answer tests across **every** `BlockCipherCore`.
 *
 * ## Why a round-trip proves almost nothing here
 *
 * CFB's two directions differ in one wire, so a round-trip at least exercises
 * both wirings. OFB has no such wire: its register is refilled from the
 * cipher's own output, which is message-independent, so encrypt and decrypt are
 * **structurally the same spec**. Running one and then the other therefore
 * round-trips *by construction* — XOR is self-inverse over an identical
 * keystream — and would keep round-tripping even if the keystream were
 * generated by an entirely wrong rule. The round-trip test below is kept for
 * completeness and asserted last; it carries no weight.
 *
 * What actually discriminates a correct OFB is the keystream recurrence:
 *
 *   O_0 = IV      O_j = E_K(O_{j-1})      C_i = P_i ⊕ O_{i+1}
 *
 * Three oracles pin it, none of which a self-consistent-but-wrong pair passes:
 *
 * 1. **External, for AES** — `node:crypto`'s `aes-{128,192,256}-ofb`. Unlike
 *    CFB there is no `-ofb8`/`-ofb1` variant to confuse it with; SP 800-38A
 *    §6.4 fixes the feedback at the full block.
 * 2. **Constructed-from-ECB, for every core** — the register chain is rebuilt
 *    below from first principles, each register encrypted through the core's
 *    *own already-KAT-verified* ECB spec. Not circular: ECB is pinned against
 *    published vectors in the per-cipher KAT files, and the feedback rule is
 *    re-implemented here independently of the builder.
 * 3. **The three-way mode contrast** — CTR, CFB and OFB all produce block 0's
 *    keystream as `E(IV)`, so their first blocks are byte-identical. They
 *    diverge from block 1: CTR encrypts `IV+1`, CFB encrypts `C_0`, OFB
 *    encrypts `E(IV)`. A mode that is quietly one of its neighbours is caught
 *    here and nowhere else.
 *
 * A structural check backs them up: OFB has **zero error propagation** — one
 * corrupt ciphertext byte damages exactly that plaintext byte and nothing else.
 * That follows only if no ciphertext ever reaches the register, which is
 * precisely the property separating OFB from CFB (whose same test asserts two
 * damaged blocks).
 *
 * References: NIST SP 800-38A §6.4 (OFB).
 */

import { createCipheriv, createDecipheriv } from "node:crypto";
import { aesCore } from "@/ciphers/aes-core";
import type { BlockCipherCore } from "@/ciphers/block-cipher-core";
import { blowfishCore } from "@/ciphers/blowfish-core";
import { buildDefaultRegistry } from "@/ciphers/default-registry";
import { desCore } from "@/ciphers/des-core";
import { buildCfbSpec } from "@/ciphers/modes/cfb";
import { buildCtrSpec } from "@/ciphers/modes/ctr";
import { buildEcbSpec } from "@/ciphers/modes/ecb";
import { buildOfbSpec } from "@/ciphers/modes/ofb";
import { serpentCore } from "@/ciphers/serpent-core";
import { speck32_64Core } from "@/ciphers/speck-32-64-core";
import { twofishCore } from "@/ciphers/twofish-core";
import { runSpec } from "@/core/runtime";
import { bytesFromHex, hexFromBytes, makeBytesState } from "@/core/state/bytes";
import type { AuxValue, CipherSpec } from "@/core/types";
import { hasBlockCipherCore } from "@/ui/stores/block-cipher-cores";
import type { Cipher } from "@/ui/stores/cipher";
import { isCipherModeSupported } from "@/ui/stores/cipher-mode";
import { paddingLimits } from "@/ui/stores/padding";
import { describe, expect, it } from "vitest";

// ─── The cores under test ─────────────────────────────────────────────────────

/**
 * Mirrors `BLOCK_CIPHER_CORES` in `stores/block-cipher-cores.ts` (which isn't
 * exported). The "covers every cored cipher" test below fails if the two drift,
 * so a new core cannot land without gaining OFB coverage here.
 */
const CORES: ReadonlyArray<{ cipher: Cipher; core: BlockCipherCore }> = [
  { cipher: "aes-128", core: aesCore("aes-128") },
  { cipher: "aes-192", core: aesCore("aes-192") },
  { cipher: "aes-256", core: aesCore("aes-256") },
  { cipher: "speck-32-64-be", core: speck32_64Core("be-paper") },
  { cipher: "speck-32-64-le", core: speck32_64Core("le-nsa") },
  { cipher: "blowfish", core: blowfishCore() },
  { cipher: "des", core: desCore() },
  { cipher: "serpent-128", core: serpentCore(16) },
  { cipher: "serpent-192", core: serpentCore(24) },
  { cipher: "serpent-256", core: serpentCore(32) },
  { cipher: "twofish", core: twofishCore },
];

const ALL_CIPHERS: readonly Cipher[] = [
  "aes-128",
  "aes-192",
  "aes-256",
  "speck-32-64-be",
  "speck-32-64-le",
  "blowfish",
  "des",
  "serpent-128",
  "serpent-192",
  "serpent-256",
  "twofish",
];

// ─── Deterministic per-core test material ─────────────────────────────────────

/** A fixed, nonzero, non-patterned byte at index i — no accidental symmetry. */
const fillByte = (i: number): number => (i * 37 + 11) & 0xff;
const fillHex = (n: number): string =>
  Array.from({ length: n }, (_, i) => fillByte(i).toString(16).padStart(2, "0")).join("");

const keyFor = (core: BlockCipherCore): string => fillHex(core.keyByteLength);

/** Initial output-feedback register O₀, one block wide. */
const ivFor = (core: BlockCipherCore): string => fillHex(core.blockByteLength);

/**
 * Four blocks, with blocks 0 and 2 identical. Under ECB those would encrypt
 * identically; under OFB each block meets a different keystream block, so they
 * must not.
 */
const plaintextFor = (core: BlockCipherCore): string => {
  const b = core.blockByteLength;
  const blk0 = fillHex(b);
  const blk1 = fillHex(b).split("").reverse().join("");
  const blk3 = "a".repeat(b * 2);
  return `${blk0}${blk1}${blk0}${blk3}`;
};

// ─── Running the app's real specs ─────────────────────────────────────────────

const runMode = (spec: CipherSpec, inputHex: string, keyHex: string, ivHex?: string): string => {
  const aux = new Map<string, AuxValue>([["key", bytesFromHex(keyHex)]]);
  if (ivHex !== undefined) aux.set("iv", bytesFromHex(ivHex));
  const trace = runSpec(spec, buildDefaultRegistry(), {
    initialState: makeBytesState(bytesFromHex(inputHex)),
    initialAux: aux,
  });
  if (trace.finalState.shape !== "bytes") throw new Error("expected bytes final state");
  return hexFromBytes(trace.finalState.bytes);
};

// ─── The constructed oracle: OFB rebuilt on top of the core's verified ECB ────

/**
 * Expected OFB output, built from first principles.
 *
 * The register starts at the IV and is replaced each iteration by its **own
 * encryption** — never by anything derived from the message. Note there is no
 * `direction` parameter, and that absence is the point: the keystream is
 * identical whichever way the spec runs, so one oracle serves both.
 *
 * Necessarily serial, and for a reason worth naming: register j+1 is register
 * j's ciphertext, so reaching block n costs n encryptions. CTR's oracle can
 * jump straight to any block by adding to its counter. That is the practical
 * difference between the two modes.
 */
const ofbOracle = (core: BlockCipherCore, inputHex: string, keyHex: string, ivHex: string) => {
  const b = core.blockByteLength;
  const input = bytesFromHex(inputHex);
  const ecb = buildEcbSpec(core, "encrypt");

  let register = bytesFromHex(ivHex);
  const out = new Uint8Array(input.length);

  for (let off = 0; off < input.length; off += b) {
    const block = input.subarray(off, Math.min(off + b, input.length));
    // The register is ALWAYS a full block wide — that is what keeps the core
    // untouched by the ragged tail.
    const keystream = bytesFromHex(runMode(ecb, hexFromBytes(register), keyHex));
    for (let i = 0; i < block.length; i++) {
      out[off + i] = (block[i] as number) ^ (keystream[i] as number);
    }
    // THE line: the register becomes the keystream block itself — the full,
    // untrimmed cipher output, not the (possibly short) XOR result.
    register = keystream;
  }
  return hexFromBytes(out);
};

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("OFB across every BlockCipherCore", () => {
  it("covers every cipher that has a core (guards against a new core skipping OFB)", () => {
    const cored = ALL_CIPHERS.filter((c) => hasBlockCipherCore(c));
    expect(CORES.map((e) => e.cipher).sort()).toEqual([...cored].sort());
  });

  it("every cored cipher advertises OFB in the mode table", () => {
    for (const { cipher } of CORES) {
      expect(isCipherModeSupported(cipher, "ofb")).toBe(true);
    }
  });

  // ── The external oracle: AES vs node:crypto ────────────────────────────────
  describe("AES — byte-equal to node:crypto's aes-*-ofb (external oracle)", () => {
    for (const variant of ["aes-128", "aes-192", "aes-256"] as const) {
      const core = aesCore(variant);
      const key = keyFor(core);
      const iv = ivFor(core);
      const pt = plaintextFor(core);

      it(`${variant} encrypt matches node's ${variant}-ofb`, () => {
        const c = createCipheriv(`${variant}-ofb`, bytesFromHex(key), bytesFromHex(iv));
        const expected = Buffer.concat([c.update(Buffer.from(pt, "hex")), c.final()]).toString(
          "hex",
        );
        expect(runMode(buildOfbSpec(core, "encrypt"), pt, key, iv)).toBe(expected);
      });

      it(`${variant} decrypt of an ARBITRARY buffer matches node (no encrypt run involved)`, () => {
        // Decrypting a buffer that was never a ciphertext is the assertion the
        // free round-trip cannot make: there is no encrypt run to conspire with,
        // so the keystream must be right on its own terms.
        const d = createDecipheriv(`${variant}-ofb`, bytesFromHex(key), bytesFromHex(iv));
        const expected = Buffer.concat([d.update(Buffer.from(pt, "hex")), d.final()]).toString(
          "hex",
        );
        expect(runMode(buildOfbSpec(core, "decrypt"), pt, key, iv)).toBe(expected);
      });

      it(`${variant} keystream is the E-chain over the IV, not the counter or the ciphertext`, () => {
        // XOR a zero message with the keystream to read it out directly, then
        // check it block by block against E(IV), E(E(IV)), E(E(E(IV))). This is
        // the recurrence itself, asserted without reference to any oracle but
        // node's raw single-block ECB.
        const b = core.blockByteLength;
        const zeros = "00".repeat(4 * b);
        const ks = bytesFromHex(runMode(buildOfbSpec(core, "encrypt"), zeros, key, iv));
        let register = bytesFromHex(iv);
        for (let i = 0; i < 4; i++) {
          const e = createCipheriv(`${variant}-ecb`, bytesFromHex(key), null);
          e.setAutoPadding(false);
          const next = Buffer.concat([e.update(Buffer.from(register)), e.final()]);
          expect(hexFromBytes(ks.subarray(i * b, (i + 1) * b))).toBe(next.toString("hex"));
          register = new Uint8Array(next);
        }
      });
    }
  });

  // ── The three-way mode contrast ────────────────────────────────────────────
  describe("OFB is neither CTR nor CFB (the modes it shares block 0 with)", () => {
    for (const { cipher, core } of CORES) {
      const key = keyFor(core);
      const iv = ivFor(core);
      const pt = plaintextFor(core);
      const hexBlock = core.blockByteLength * 2;

      it(`${cipher}: block 0 is identical across CTR/CFB/OFB, block 1 differs in all three`, () => {
        // All three encrypt the IV for block 0's keystream, so their first
        // blocks must agree — a good sanity check that the IV reaches the same
        // place in each. From block 1 they must all disagree: CTR advances to
        // IV+1, CFB loads C₀, OFB loads E(IV). If OFB's tail matched either
        // neighbour, it would be that mode wearing OFB's name.
        const ofb = runMode(buildOfbSpec(core, "encrypt"), pt, key, iv);
        const ctr = runMode(buildCtrSpec(core, "encrypt"), pt, key, iv);
        const cfb = runMode(buildCfbSpec(core, "encrypt"), pt, key, iv);

        expect(ofb.slice(0, hexBlock)).toBe(ctr.slice(0, hexBlock));
        expect(ofb.slice(0, hexBlock)).toBe(cfb.slice(0, hexBlock));

        expect(ofb.slice(hexBlock)).not.toBe(ctr.slice(hexBlock));
        expect(ofb.slice(hexBlock)).not.toBe(cfb.slice(hexBlock));
      });
    }
  });

  // ── The constructed oracle + structural properties, per core ───────────────
  for (const { cipher, core } of CORES) {
    describe(`${cipher} (${core.blockByteLength}-byte block)`, () => {
      const key = keyFor(core);
      const iv = ivFor(core);
      const pt = plaintextFor(core);
      const b = core.blockByteLength;
      const hexBlock = b * 2;

      it("encrypts to keystream ⊕ message, the keystream being its own ECB iterated over the IV", () => {
        expect(runMode(buildOfbSpec(core, "encrypt"), pt, key, iv)).toBe(
          ofbOracle(core, pt, key, iv),
        );
      });

      it("encrypt and decrypt are the SAME transformation — identical output on identical input", () => {
        // The property that makes OFB's round-trip free, asserted directly
        // rather than relied upon. Both specs must produce byte-identical
        // output for the same buffer; anything else means a direction branch
        // survived somewhere it shouldn't have.
        expect(runMode(buildOfbSpec(core, "decrypt"), pt, key, iv)).toBe(
          runMode(buildOfbSpec(core, "encrypt"), pt, key, iv),
        );
      });

      it("the keystream is independent of the message (the CFB contrast)", () => {
        // Encrypt two totally different plaintexts under the same key+IV and
        // recover the keystream from each by XORing the plaintext back out.
        // Under OFB the two keystreams are equal in EVERY block. Under CFB they
        // would agree only in block 0, because CFB's register loads the
        // ciphertext. This is the mode's defining property.
        const altPt = "00".repeat(pt.length / 2);
        const a = bytesFromHex(runMode(buildOfbSpec(core, "encrypt"), pt, key, iv));
        const z = bytesFromHex(runMode(buildOfbSpec(core, "encrypt"), altPt, key, iv));
        const p = bytesFromHex(pt);
        for (let i = 0; i < p.length; i++) {
          expect((a[i] as number) ^ (z[i] as number)).toBe(p[i] as number);
        }
      });

      it("has ZERO error propagation — one corrupt ciphertext byte damages one plaintext byte", () => {
        // The structural proof that no ciphertext ever reaches the register.
        // CFB's identical test asserts two damaged blocks; here everything
        // outside the single flipped byte must come back clean, because the
        // keystream was fixed before any ciphertext existed.
        const ct = bytesFromHex(runMode(buildOfbSpec(core, "encrypt"), pt, key, iv));
        const corrupted = new Uint8Array(ct);
        corrupted[b] = (corrupted[b] as number) ^ 0x80; // first byte of block 1
        const got = bytesFromHex(
          runMode(buildOfbSpec(core, "decrypt"), hexFromBytes(corrupted), key, iv),
        );
        const clean = bytesFromHex(pt);

        expect(got[b]).toBe((clean[b] as number) ^ 0x80);
        // Every other byte in the whole message is untouched.
        for (let i = 0; i < clean.length; i++) {
          if (i === b) continue;
          expect(got[i]).toBe(clean[i]);
        }
      });

      it("does NOT leak the repeated plaintext block that ECB leaks", () => {
        // Blocks 0 and 2 are identical plaintext but meet different keystream
        // blocks, so they must not encrypt identically.
        const ct = runMode(buildOfbSpec(core, "encrypt"), pt, key, iv);
        expect(ct.slice(0, hexBlock)).not.toBe(ct.slice(2 * hexBlock, 3 * hexBlock));
      });

      it("a different IV changes the entire ciphertext", () => {
        const ctA = runMode(buildOfbSpec(core, "encrypt"), pt, key, iv);
        const zeroIv = "00".repeat(b);
        const ctB = runMode(buildOfbSpec(core, "encrypt"), pt, key, zeroIv);
        expect(ctB).not.toBe(ctA);
        expect(ctB).toBe(ofbOracle(core, pt, key, zeroIv));
      });

      it("needs NO padding — a short message encrypts to an equally short ciphertext", () => {
        const short = "7e".repeat(b - 1);
        const ct = runMode(buildOfbSpec(core, "encrypt"), short, key, iv);
        expect(ct.length / 2).toBe(b - 1);
        expect(ct).toBe(ofbOracle(core, short, key, iv));
        expect(runMode(buildOfbSpec(core, "decrypt"), ct, key, iv)).toBe(short);
      });

      it("handles a message that is neither a whole block nor shorter than one", () => {
        // The genuinely ragged case: a full block plus a remainder, so both the
        // full-width path and the trim path run in the same trace. The trim
        // must not have reached the feedback register — but note that on a
        // final short block nothing reads the register again, so this test
        // pins the OUTPUT, not the wiring choice. (The wiring is argued in the
        // mode file's header; it is unobservable by construction.)
        const ragged = `${fillHex(b)}7e7e`;
        const ct = runMode(buildOfbSpec(core, "encrypt"), ragged, key, iv);
        expect(ct.length).toBe(ragged.length);
        expect(ct).toBe(ofbOracle(core, ragged, key, iv));
        expect(runMode(buildOfbSpec(core, "decrypt"), ct, key, iv)).toBe(ragged);
      });

      it("paddingLimits gives OFB the stream-mode bounds, not CBC's block-aligned ones", () => {
        expect(paddingLimits("decrypt", "none", cipher, "ofb").min).toBe(1);
        expect(paddingLimits("encrypt", "none", cipher, "ofb").min).toBe(1);
        // CBC keeps the block floor — the relaxation must not have leaked.
        expect(paddingLimits("decrypt", "none", cipher, "cbc").min).toBe(b);
      });

      it("round-trips plaintext → ciphertext → plaintext (free, and asserted last)", () => {
        const ct = runMode(buildOfbSpec(core, "encrypt"), pt, key, iv);
        expect(runMode(buildOfbSpec(core, "decrypt"), ct, key, iv)).toBe(pt);
        expect(ct).not.toBe(pt);
      });
    });
  }
});
