/**
 * `zq-byte-encode@1` / `zq-byte-decode@1` — FIPS 203 Algorithms 5 and 6
 * (ML-KEM P2, `docs/plans/unified-stargazing-quasar.md`).
 *
 * The dense `d`-bit packing. P2's plan names this as one of three independent
 * places to be subtly wrong that P3's aggregate `ek` comparison catches only in
 * combination — a compensating pair of errors survives it — so it is pinned here
 * directly, three ways, in ascending order of how much they prove.
 *
 * ## Rank 1 — a real ML-KEM-768 encapsulation key, produced elsewhere
 *
 * `EK_FIXTURE` below is the first 1152 bytes (the three encoded polynomials of
 * `t̂`, before the 32-byte `ρ`) of a genuine ML-KEM-768 public key generated by
 * **Node 24's OpenSSL**, not by anything in this repository. Two properties make
 * it a real oracle for the bit order rather than a smoke test:
 *
 *  - Decoding it as FIPS 203 does yields 768 coefficients **all inside
 *    `[0, q)`** — while 12 bits can express 4096 values, so a wrong bit order
 *    lands out of range constantly. Measured, not asserted on faith: reversing
 *    the bit-in-byte order puts 169 of the 768 coefficients out of range,
 *    reversing the bit-in-coefficient order 162, reversing both 71. Those three
 *    perturbations are run below.
 *  - Re-encoding those coefficients reproduces the fixture **byte for byte**,
 *    which pins encode and decode against an external artifact rather than
 *    against each other.
 *
 * The key is NOT reproducible from a seed on that build: `generateKeyPairSync`
 * accepts a `seed` option and **silently ignores it** on Node v24.14.1, so
 * successive calls give different keys (the plan's P3/P4 oracle assumes
 * otherwise — see the note recorded there). It does not matter here, because any
 * valid `ek` pins the encoding equally well; it is captured as bytes rather than
 * regenerated so the test also runs on CI, which is on Node 22 and has no
 * ML-KEM at all. To refresh it on a Node ≥ 24 machine:
 *
 * ```
 * const spki = crypto.generateKeyPairSync("ml-kem-768").publicKey
 *   .export({ type: "spki", format: "der" });
 * spki.subarray(spki.length - 1184, spki.length - 32).toString("hex");
 * ```
 *
 * ## Rank 2 — the algorithms written out from the specification
 *
 * `BitsToBytes` / `BytesToBits` (Algorithms 3 and 4) written literally as bit
 * arrays, then `ByteEncode_d` / `ByteDecode_d` on top of them. Verbose on
 * purpose: it shares no code with the executors, which pack with shifts.
 *
 * ## Rank 3 — round-trip
 *
 * Last, and treated as such. Encode and decode being exact inverses says nothing
 * about whether either matches anybody else's — the CFB lesson.
 */

import { buildDefaultRegistry } from "@/ciphers/default-registry";
import type { Json, StepContext } from "@/core/types";
import { zqByteDecode } from "@/steps/zq-byte-decode";
import { zqByteEncode } from "@/steps/zq-byte-encode";
import { describe, expect, it } from "vitest";

const ctx: StepContext = { stepId: "t", path: [], aux: new Map() };
const Q = 3329;
const Q_BYTES = new Uint8Array([0x0d, 0x01]);
const params = (d: number, littleEndian = false): Json => ({ coeffBytes: 2, littleEndian, d });

/**
 * `ByteEncode_12(t̂)` from a real ML-KEM-768 encapsulation key — Node 24's
 * OpenSSL. Three polynomials × 384 bytes. See the file header.
 */
const EK_FIXTURE_HEX = [
  "f9c29822f1a1f3d3685edc93619b5aa2120c83f8adf2374614c41aa257a593d96ac8736875903ea67371955669bf3c95",
  "73f1ba42922fb1f4b02b523b7d4c26b5eb84524159ce67726a4265e75aa4f1d27c2656a8aa621fbce65f8e2916540183",
  "d629780317151f5060bcca928fa598a9c76e1ab237b6fb306eca7f84cc18d027438e7b098840a464308c4d59a70a9101",
  "4e2a1b2e22a74e30939b0215abfb08d81a8b5ffb5a962b52f9991585205c55cbbaabca04c0021e28875e729c61043b34",
  "99fb7ec7486e87d960f35a5b2c46875222c6df6968940ac9fd603aed14618e68bd9d9c872af102b5860a8f6138d472c0",
  "7e507426f3718f6bab4ea5b694398ba2765721473c06f0c251ac220dc00e6d437e39b011d4950a87f4765bc52950f51f",
  "62177d3a0c39bd286c4e59106bd04c9f6426a850268b52b2fd347b2e478e8a702ceddb6b7fc5a8ed72a40cb23ed352a0",
  "4a7aae3907228ee5c20cb86ba6a9093fb7637699685f6a25ade6127ac49b430199143c45793898ece667dcaaadb39201",
  "18c71ce6551f2e5b99ee484037b58c856a5164d7102d524ad92551a4015771a3000bab4d28a9927211a0a4ac5a908810",
  "c305033a2a62321a9cfe31560aa02ae5bc205d9638fa8638728c8fe0886c7088233a205f03a33994287db4b4223c3194",
  "b5614c046a51e183249fbb3927c1ccf9850bf56c0672057b23a65098750bdd5c51e83688610664b4caad9c1c82352ba4",
  "f9bb0d1aa507359cad0a3ca37a6cc6f6a04e1da145145c64e8683291645b47a3c37f620aeee159c844b5b686583af7b5",
  "44167f8fb45ae3d36541796411e52b53fcbb96336bcfc77704fba0df102a7dc5cb9983bde9e674c22441786b26b65719",
  "9fe1cf85eb809e7048d7f091e0003504f439753882d7e39554fb35b211351c266f7de5123532774967808d9589c05ca7",
  "f7c1669f45c001dccf3d02202103964e2232ed34b92ffc7f53695d28314e578167544cb1da63c9874bb485c98378057e",
  "08598db7d41f613c7501738b88a965fc2411e64573e4479877e2cd34e5a981b816a35c50ced00edbc453ce538cf906b9",
  "fa03ae42581b5d0949cbc2ca24f4b836354efb610d929acdad1965b76b6ba8e76e3b1b5b48a046b3714ce0936113a0a0",
  "d0fc4ff0198c1f998f2b2708f3f67f10298abfa68f3d09363b6aa505593dbcd9aa1b0b427b0ba3570a171e8b429542c2",
  "3325c6592468464b3500fcb14219291142c81e4bacedaaade518ac0e16c958922bb51101a22b6c0a461678882c7b2447",
  "02c732767cc0726216d4587c62ec071bdb8b8d7028e317ab2ef5462185c7718a5752b58f0e20a0fea748800ba14a8254",
  "106c176c210fb9872378652c671397fa4b1ee568bb18954abf48072919a6eb677847447db3220532d15f01140aee0b3a",
  "f0dc0ab9189f6bb744f7c12712cb5d7220800bf1c955402baa8968a0d25b28f8b2f57c378312a577f103c4e4bff8f341",
  "55cb36f4ec6bdc5b01f52c5cf52052a53287916b2f661b73c0f642091679f61c27223572bb279d1a862ea2710e661514",
  "4cf7c2673b557dfb7ce25492d6c14ab7455145b478068a44f69728371c8bbba00d1b16171ff752a0d95ee4c52077178b",
].join("");

const hexToBytes = (hex: string): Uint8Array => {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
};
const bytesToHex = (bytes: Uint8Array): string =>
  Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");

const EK_FIXTURE = hexToBytes(EK_FIXTURE_HEX);

const packBE = (coeffs: readonly number[]): Uint8Array => {
  const out = new Uint8Array(coeffs.length * 2);
  coeffs.forEach((c, i) => {
    out[i * 2] = (c >>> 8) & 0xff;
    out[i * 2 + 1] = c & 0xff;
  });
  return out;
};
const unpackBE = (bytes: Uint8Array): number[] => {
  const out: number[] = [];
  for (let i = 0; i < bytes.length; i += 2)
    out.push((bytes[i] as number) * 256 + (bytes[i + 1] as number));
  return out;
};

const runEncode = (coeffs: readonly number[], d: number, le = false): Uint8Array =>
  zqByteEncode(
    new Map([
      ["a", packBE(coeffs)],
      ["modulus", Q_BYTES],
    ]),
    params(d, le),
    ctx,
  ).get("output") as Uint8Array;

const runDecode = (packed: Uint8Array, d: number, le = false): number[] => {
  const out = zqByteDecode(
    new Map([
      ["a", packed],
      ["modulus", Q_BYTES],
    ]),
    params(d, le),
    ctx,
  ).get("output") as Uint8Array;
  return le
    ? Array.from(
        { length: out.length / 2 },
        (_, i) => (out[i * 2 + 1] as number) * 256 + (out[i * 2] as number),
      )
    : unpackBE(out);
};

// ─── The specification, written out as bit arrays ─────────────────────────

/** FIPS 203 Algorithm 3 — BitsToBytes. Bit `i` becomes bit `i mod 8` of byte `i div 8`. */
const bitsToBytes = (bits: readonly number[]): Uint8Array => {
  const out = new Uint8Array(bits.length / 8);
  bits.forEach((bit, i) => {
    out[Math.floor(i / 8)] = (out[Math.floor(i / 8)] as number) + bit * 2 ** (i % 8);
  });
  return out;
};

/** FIPS 203 Algorithm 4 — BytesToBits. */
const bytesToBits = (bytes: Uint8Array): number[] => {
  const bits: number[] = [];
  for (const byte of bytes) {
    let c = byte;
    for (let j = 0; j < 8; j++) {
      bits.push(c % 2);
      c = (c - (c % 2)) / 2;
    }
  }
  return bits;
};

/** FIPS 203 Algorithm 5 — ByteEncode_d, straight from the pseudocode. */
const byteEncodeSpec = (coeffs: readonly number[], d: number): Uint8Array => {
  const bits: number[] = [];
  for (const value of coeffs) {
    let a = value;
    for (let j = 0; j < d; j++) {
      const bit = a % 2;
      bits.push(bit);
      a = (a - bit) / 2;
    }
  }
  return bitsToBytes(bits);
};

/** FIPS 203 Algorithm 6 — ByteDecode_d, straight from the pseudocode. */
const byteDecodeSpec = (packed: Uint8Array, d: number): number[] => {
  const bits = bytesToBits(packed);
  const m = 2 ** d < Q ? 2 ** d : Q;
  const n = bits.length / d;
  return Array.from({ length: n }, (_, i) => {
    let v = 0;
    for (let j = 0; j < d; j++) v += (bits[i * d + j] as number) * 2 ** j;
    return v % m;
  });
};

/** Decode with one ordering deliberately reversed — the perturbations. */
const decodePerturbed = (
  packed: Uint8Array,
  d: number,
  reverseBitInByte: boolean,
  reverseBitInCoeff: boolean,
): number[] => {
  const n = (packed.length * 8) / d;
  return Array.from({ length: n }, (_, i) => {
    let v = 0;
    for (let j = 0; j < d; j++) {
      const t = i * d + j;
      const shift = reverseBitInByte ? 7 - (t % 8) : t % 8;
      if ((((packed[t >> 3] as number) >> shift) & 1) === 1)
        v |= 1 << (reverseBitInCoeff ? d - 1 - j : j);
    }
    return v;
  });
};

const ML_KEM_DS = [1, 4, 5, 10, 11, 12] as const;
const ALL_DS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const;

/** A deterministic spread of legal coefficients for a given d. */
const sample = (n: number, d: number): number[] => {
  const limit = Math.min(2 ** d, Q);
  return Array.from({ length: n }, (_, i) => (i * 719 + 13) % limit);
};

// ─── Rank 1: a real ML-KEM key, produced outside this repository ──────────

describe("a genuine ML-KEM-768 encapsulation key pins the bit order", () => {
  it("decodes the three encoded polynomials into 768 coefficients, every one inside [0, q)", () => {
    // 12 bits can express 4096 values and the ring has 3329, so ~19% of random
    // 12-bit values are out of range. 768 in a row landing in range is not luck.
    //
    // Read RAW — `decodePerturbed` with no perturbation — rather than through
    // `runDecode`. FIPS 203's ByteDecode_d ends in `mod min(2^d, q)` and the
    // shipped step faithfully does the same, so a range check made through it
    // can never fail whatever bytes go in. (Found while writing P3's fixture
    // test, which had inherited the same vacuous shape.) The `runDecode` path
    // is still pinned against this key, by the re-encode test below.
    const coeffs = [0, 1, 2].flatMap((p) =>
      decodePerturbed(EK_FIXTURE.subarray(p * 384, (p + 1) * 384), 12, false, false),
    );
    expect(coeffs).toHaveLength(768);
    expect(coeffs.filter((c) => c >= Q)).toEqual([]);
    // ...and the shipped step agrees with the raw read, its reduction never
    // firing, which is what makes the two checks one check.
    expect(
      [0, 1, 2].flatMap((p) => runDecode(EK_FIXTURE.subarray(p * 384, (p + 1) * 384), 12)),
    ).toEqual(coeffs);
  });

  it("re-encodes those coefficients back to the key's own bytes, exactly", () => {
    // This is the assertion that pins encode and decode against an EXTERNAL
    // artifact rather than against each other.
    const rebuilt = [0, 1, 2].map((p) =>
      bytesToHex(runEncode(runDecode(EK_FIXTURE.subarray(p * 384, (p + 1) * 384), 12), 12)),
    );
    expect(rebuilt.join("")).toBe(EK_FIXTURE_HEX);
  });

  it("every wrong bit order puts coefficients out of range — the perturbations are run, not assumed", () => {
    // Measured counts, so a future change that quietly makes one of these pass
    // is visible rather than merely un-asserted.
    const poly0 = EK_FIXTURE.subarray(0, 384);
    const outOfRange = (rb: boolean, rc: boolean) =>
      decodePerturbed(poly0, 12, rb, rc).filter((c) => c >= Q).length;
    expect(outOfRange(false, false)).toBe(0); // FIPS 203's order
    expect(outOfRange(true, false)).toBeGreaterThan(20); // bit-in-byte reversed
    expect(outOfRange(false, true)).toBeGreaterThan(20); // bit-in-coefficient reversed
    expect(outOfRange(true, true)).toBeGreaterThan(20); // both
  });

  it("produces the sizes ML-KEM publishes — 384 bytes per polynomial at d = 12", () => {
    // 256 coefficients × 12 bits = 384 bytes, so ML-KEM-768's t̂ (three
    // polynomials) is 1152 bytes and its ek is 1184 with ρ appended. This is
    // the whole reason the packing exists rather than shipping 512-byte
    // polynomials.
    expect(runEncode(sample(256, 12), 12)).toHaveLength(384);
    expect(EK_FIXTURE).toHaveLength(1152);
    expect(runEncode(sample(256, 10), 10)).toHaveLength(320);
    expect(runEncode(sample(256, 1), 1)).toHaveLength(32);
  });
});

// ─── Rank 2: the specification's own algorithms ───────────────────────────

describe("zq-byte-encode@1 / zq-byte-decode@1 match FIPS 203 Algorithms 5 and 6", () => {
  it("encodes exactly as ByteEncode_d does, for every d in 1..12", () => {
    for (const d of ALL_DS) {
      const coeffs = sample(256, d);
      expect({ d, out: bytesToHex(runEncode(coeffs, d)) }).toEqual({
        d,
        out: bytesToHex(byteEncodeSpec(coeffs, d)),
      });
    }
  });

  it("decodes exactly as ByteDecode_d does, for every d in 1..12", () => {
    for (const d of ALL_DS) {
      const packed = runEncode(sample(256, d), d);
      expect({ d, out: runDecode(packed, d) }).toEqual({ d, out: byteDecodeSpec(packed, d) });
    }
  });

  it("reduces mod q at d = 12 and only at d = 12 — the malformed-input guard", () => {
    // 12 bits can carry 4095, which is not a ring element. FIPS 203's rule is
    // `m = q` for d = 12 and `m = 2^d` below it; the executor spells that as
    // min(2^d, q) so it generalises instead of hardcoding 12.
    const packed = byteEncodeSpec([4095, 3329, 3328, 0], 12);
    expect(runDecode(packed, 12)).toEqual([4095 - Q, 0, 3328, 0]);

    // At d = 11 every representable value is already a ring element, so nothing
    // is ever reduced — asserted so the guard cannot creep downward.
    const wide = Array.from({ length: 2048 }, (_, i) => i);
    expect(runDecode(runEncode(wide, 11), 11)).toEqual(wide);
  });

  it("packs across byte boundaries — coefficients do NOT start on byte edges", () => {
    // The defining property of a dense packing, and the one a naive
    // one-coefficient-per-slot implementation gets wrong while still passing a
    // length check. At d = 12 the second coefficient begins in the middle of
    // byte 1: value 1 then 1 must not produce 01 00 01 00.
    expect(bytesToHex(runEncode([1, 1], 12))).toBe("011000");
    expect(runDecode(hexToBytes("011000"), 12)).toEqual([1, 1]);
  });
});

// ─── Rank 3: round-trip, last and least ───────────────────────────────────

describe("round-trip — ranked last, because it proves the least", () => {
  it("recovers every coefficient for every d in 1..12", () => {
    // A matched-wrong encoder and decoder pass this happily. It is here to
    // catch an asymmetry, not to establish correctness.
    for (const d of ALL_DS) {
      const coeffs = sample(256, d);
      expect({ d, out: runDecode(runEncode(coeffs, d), d) }).toEqual({ d, out: coeffs });
    }
  });

  it("survives the full legal range at each d ML-KEM uses", () => {
    for (const d of ML_KEM_DS) {
      const limit = Math.min(2 ** d, Q);
      const coeffs = Array.from({ length: limit }, (_, i) => i);
      // Pad to a whole number of bytes; the step refuses a partial byte.
      while ((coeffs.length * d) % 8 !== 0) coeffs.push(0);
      expect({ d, ok: runDecode(runEncode(coeffs, d), d) }).toEqual({ d, ok: coeffs });
    }
  });
});

// ─── Wiring ───────────────────────────────────────────────────────────────

describe("wiring and loud failures", () => {
  it("is registered under both bare names", () => {
    const r = buildDefaultRegistry();
    expect(r.has("zq-byte-encode@1")).toBe(true);
    expect(r.has("zq-byte-decode@1")).toBe(true);
    expect(r.getDoc("zq-byte-encode@1")).toBeDefined();
    expect(r.getDoc("zq-byte-decode@1")).toBeDefined();
  });

  it("throws on a coefficient too large for d rather than dropping its top bits", () => {
    // Pairs, not singletons: one coefficient at d = 4 is half a byte, so the
    // byte-alignment check would fire first and this would pass for the wrong
    // reason.
    expect(() => runEncode([16, 0], 4)).toThrow(/does not fit 4 bits/);
    // At d = 12 the ring, not the bit width, is the ceiling.
    expect(() => runEncode([3329, 0], 12)).toThrow(/does not fit 12 bits/);
    expect(() => runEncode([3328, 0], 12)).not.toThrow();
  });

  it("throws when the bits do not fill a whole number of bytes", () => {
    // 3 coefficients × 12 bits = 36 bits. There is no room for half a byte.
    expect(() => runEncode([1, 2, 3], 12)).toThrow(/whole number of bytes/);
    expect(() => runDecode(new Uint8Array(5), 12)).toThrow(/whole number of 12-bit/);
  });

  it("throws on a missing modulus port", () => {
    expect(() => zqByteEncode(new Map([["a", packBE([1, 1])]]), params(8), ctx)).toThrow(/modulus/);
    expect(() => zqByteDecode(new Map([["a", new Uint8Array(2)]]), params(8), ctx)).toThrow(
      /modulus/,
    );
  });

  it("littleEndian moves the coefficient SLOTS, never the packed bit order", () => {
    // The trap the step's header warns about three times. Same numbers in, so
    // the packed output must be byte-identical under either convention — only
    // the layout of the vector port changes.
    const coeffs = sample(16, 12);
    const be = runEncode(coeffs, 12, false);
    const leVector = new Uint8Array(coeffs.length * 2);
    coeffs.forEach((c, i) => {
      leVector[i * 2] = c & 0xff;
      leVector[i * 2 + 1] = (c >>> 8) & 0xff;
    });
    const le = zqByteEncode(
      new Map([
        ["a", leVector],
        ["modulus", Q_BYTES],
      ]),
      params(12, true),
      ctx,
    ).get("output") as Uint8Array;
    expect(bytesToHex(le)).toBe(bytesToHex(be));
  });
});
